package handlers_test

import (
	"bytes"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"path/filepath"
	"strings"
	"testing"

	"github.com/giovanibalarini/linkguard-fw/internal/api/handlers"
	"github.com/giovanibalarini/linkguard-fw/internal/firewall"
	"github.com/giovanibalarini/linkguard-fw/internal/secrets"
	"github.com/giovanibalarini/linkguard-fw/internal/storage"
	"github.com/giovanibalarini/linkguard-fw/internal/wireguard"
)

func newVPNTestHandler(t *testing.T) (*handlers.VPNHandler, *storage.DB, secrets.Secrets) {
	t.Helper()
	dir := t.TempDir()
	db, err := storage.Open(filepath.Join(dir, "test.db"))
	if err != nil {
		t.Fatalf("Open: %v", err)
	}
	t.Cleanup(func() { db.Close() })

	key, err := secrets.LoadOrGenerateKey(filepath.Join(dir, "secret.key"))
	if err != nil {
		t.Fatalf("LoadOrGenerateKey: %v", err)
	}
	sec := secrets.NewService(db, key)

	svc := wireguard.NewService(firewall.NewDryRunExecutor())
	h := handlers.NewVPNHandler(db, svc, sec)
	return h, db, sec
}

// TestVPNPeerPrivateKeyNeverInSettings proves the WireGuard config — including
// every private key — is stored in the secrets vault, not in the plaintext
// settings table: a backup export (ExportSettings) must never contain a
// private key, while the vault round-trips it correctly.
func TestVPNPeerPrivateKeyNeverInSettings(t *testing.T) {
	h, db, sec := newVPNTestHandler(t)

	body, _ := json.Marshal(map[string]any{"name": "laptop"})
	req := httptest.NewRequest(http.MethodPost, "/api/vpn/peers", bytes.NewReader(body))
	w := httptest.NewRecorder()
	h.AddPeer(w, req)
	if w.Code != http.StatusOK {
		t.Fatalf("AddPeer: expected 200, got %d: %s", w.Code, w.Body.String())
	}

	var resp struct {
		Peer struct {
			PrivateKey string `json:"private_key"`
		} `json:"peer"`
	}
	if err := json.Unmarshal(w.Body.Bytes(), &resp); err != nil {
		t.Fatalf("decode response: %v", err)
	}
	privKey := resp.Peer.PrivateKey
	if privKey == "" {
		t.Fatal("expected AddPeer to generate a non-empty private key")
	}

	// The settings table (what ExportSettings/backups expose) must never
	// contain the private key, nor even the "wireguard" key at all.
	settings, err := db.ExportSettings()
	if err != nil {
		t.Fatalf("ExportSettings: %v", err)
	}
	if _, present := settings["wireguard"]; present {
		t.Fatalf("expected no 'wireguard' key in settings table, found one: %v", settings["wireguard"])
	}
	for _, v := range settings {
		if strings.Contains(v, privKey) {
			t.Fatalf("private key leaked into plaintext settings table: %q", v)
		}
	}

	// The vault must have it, and round-trip it correctly.
	raw, err := sec.Get("wireguard")
	if err != nil {
		t.Fatalf("sec.Get(wireguard): %v", err)
	}
	if !strings.Contains(raw, privKey) {
		t.Fatalf("expected vault-stored config to contain the generated private key")
	}
}

// TestVPNUpdateConfigServerKeyNeverInSettings covers the server keypair
// (generated by UpdateConfig, not AddPeer) with the same guarantee.
func TestVPNUpdateConfigServerKeyNeverInSettings(t *testing.T) {
	h, db, sec := newVPNTestHandler(t)

	body, _ := json.Marshal(map[string]any{
		"enabled":     false,
		"listen_port": 51820,
		"subnet":      "10.7.0.0/24",
		"address":     "10.7.0.1/24",
	})
	req := httptest.NewRequest(http.MethodPut, "/api/vpn/config", bytes.NewReader(body))
	w := httptest.NewRecorder()
	h.UpdateConfig(w, req)
	if w.Code != http.StatusOK {
		t.Fatalf("UpdateConfig: expected 200, got %d: %s", w.Code, w.Body.String())
	}

	raw, err := sec.Get("wireguard")
	if err != nil {
		t.Fatalf("sec.Get(wireguard): %v", err)
	}
	var stored wireguard.Config
	if err := json.Unmarshal([]byte(raw), &stored); err != nil {
		t.Fatalf("unmarshal vault-stored config: %v", err)
	}
	if stored.PrivateKey == "" {
		t.Fatal("expected the generated server private key to be present in the vault")
	}

	settings, err := db.ExportSettings()
	if err != nil {
		t.Fatalf("ExportSettings: %v", err)
	}
	if _, present := settings["wireguard"]; present {
		t.Fatalf("expected no 'wireguard' key in settings table, found one: %v", settings["wireguard"])
	}
	for _, v := range settings {
		if strings.Contains(v, stored.PrivateKey) {
			t.Fatalf("server private key leaked into plaintext settings table: %q", v)
		}
	}
}
